import { i } from "@instantdb/core";

const _schema = i.schema({
  entities: {
    rooms: i.entity({
      slug: i.string().unique().indexed(),
      displayName: i.string().optional(),
      activeGameId: i.string().indexed().optional(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    roomHandles: i.entity({
      roomSlug: i.string().indexed(),
      handle: i.string().indexed(),
      normalizedHandle: i.string().indexed(),
      handleKey: i.string().unique().indexed(),
      displayName: i.string(),
      lastSeenAt: i.date(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    games: i.entity({
      roomSlug: i.string().indexed(),
      gameKey: i.string().unique().indexed(),
      status: i.string().indexed(),
      phase: i.string().indexed(),
      hostHandle: i.string().indexed(),
      currentRoundId: i.string().indexed().optional(),
      currentRoundNumber: i.number(),
      totalHarvests: i.number(),
      phaseVersion: i.number(),
      playerCount: i.number(),
      fieldPackId: i.string().indexed(),
      rulesVersion: i.string().indexed(),
      ribbons: i.json(),
      createdAt: i.date(),
      updatedAt: i.date(),
      completedAt: i.date().optional(),
    }),
    gamePlayers: i.entity({
      roomSlug: i.string().indexed(),
      gameId: i.string().indexed(),
      handle: i.string().indexed(),
      normalizedHandle: i.string().indexed(),
      gameHandleKey: i.string().unique().indexed(),
      displayName: i.string(),
      seatNumber: i.number().indexed(),
      ready: i.boolean(),
      isHost: i.boolean(),
      joinedAt: i.date(),
      updatedAt: i.date(),
    }),
    categories: i.entity({
      slug: i.string().unique().indexed(),
      label: i.string(),
      locale: i.string().indexed(),
      packId: i.string().indexed(),
      source: i.string().indexed(),
      active: i.boolean().indexed(),
      difficultyHint: i.string().indexed().optional(),
    }),
    rounds: i.entity({
      roomSlug: i.string().indexed(),
      gameId: i.string().indexed(),
      roundKey: i.string().unique().indexed(),
      roundNumber: i.number().indexed(),
      phase: i.string().indexed(),
      status: i.string().indexed(),
      farmerHandle: i.string().indexed(),
      sowerHandle: i.string().indexed(),
      fieldId: i.string().indexed().optional(),
      fieldLabel: i.string().optional(),
      depth: i.number().indexed(),
      phaseVersion: i.number(),
      publicSeedRaw: i.string().optional(),
      guessRaw: i.string().optional(),
      guessNorm: i.string().optional(),
      accepted: i.boolean().optional(),
      ribbon: i.number().optional(),
      createdAt: i.date(),
      updatedAt: i.date(),
      resolvedAt: i.date().optional(),
    }),
    roundHandleViews: i.entity({
      roomSlug: i.string().indexed(),
      gameId: i.string().indexed(),
      roundId: i.string().indexed(),
      handle: i.string().indexed(),
      normalizedHandle: i.string().indexed(),
      viewKey: i.string().unique().indexed(),
      role: i.string().indexed(),
      seatNumber: i.number().indexed(),
      seedRaw: i.string().optional(),
      seedNorm: i.string().optional(),
      offeredFieldIds: i.json().optional(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    arrows: i.entity({
      roomSlug: i.string().indexed(),
      gameId: i.string().indexed(),
      roundId: i.string().indexed(),
      arrowKey: i.string().unique().indexed(),
      rowIndex: i.number().indexed(),
      starterHandle: i.string().indexed(),
      currentHolderHandle: i.string().indexed(),
      slot: i.string().optional(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    clueEntries: i.entity({
      roomSlug: i.string().indexed(),
      gameId: i.string().indexed(),
      roundId: i.string().indexed(),
      arrowId: i.string().indexed(),
      entryKey: i.string().unique().indexed(),
      rowIndex: i.number().indexed(),
      depth: i.number().indexed(),
      handle: i.string().indexed(),
      letter: i.string(),
      sprouted: i.boolean().indexed(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    phaseLocks: i.entity({
      roomSlug: i.string().indexed(),
      gameId: i.string().indexed(),
      roundId: i.string().indexed().optional(),
      lockKey: i.string().unique().indexed(),
      purpose: i.string().indexed(),
      createdAt: i.date(),
    }),
    roundDecisions: i.entity({
      roomSlug: i.string().indexed(),
      gameId: i.string().indexed(),
      roundId: i.string().unique().indexed(),
      decisionKey: i.string().unique().indexed(),
      guessRaw: i.string(),
      guessNorm: i.string(),
      accepted: i.boolean().optional(),
      adjudicatorHandle: i.string().indexed().optional(),
      createdAt: i.date(),
      updatedAt: i.date(),
    }),
    gameEvents: i.entity({
      roomSlug: i.string().indexed(),
      gameId: i.string().indexed(),
      roundId: i.string().indexed().optional(),
      actionId: i.string().unique().indexed(),
      actorHandle: i.string().indexed(),
      type: i.string().indexed(),
      payload: i.json().optional(),
      createdAt: i.date(),
    }),
  },
  links: {
    roomHandleRoom: {
      forward: { on: "roomHandles", has: "one", label: "room" },
      reverse: { on: "rooms", has: "many", label: "handles" },
    },
    gameRoom: {
      forward: { on: "games", has: "one", label: "room" },
      reverse: { on: "rooms", has: "many", label: "games" },
    },
    gamePlayersGame: {
      forward: { on: "gamePlayers", has: "one", label: "game" },
      reverse: { on: "games", has: "many", label: "players" },
    },
    roundGame: {
      forward: { on: "rounds", has: "one", label: "game" },
      reverse: { on: "games", has: "many", label: "rounds" },
    },
    viewRound: {
      forward: { on: "roundHandleViews", has: "one", label: "round" },
      reverse: { on: "rounds", has: "many", label: "handleViews" },
    },
    arrowRound: {
      forward: { on: "arrows", has: "one", label: "round" },
      reverse: { on: "rounds", has: "many", label: "arrows" },
    },
    clueEntryArrow: {
      forward: { on: "clueEntries", has: "one", label: "arrow" },
      reverse: { on: "arrows", has: "many", label: "entries" },
    },
  },
});

type _AppSchema = typeof _schema;
export interface AppSchema extends _AppSchema {}

const schema: AppSchema = _schema;

export default schema;
